on: push

jobs:
  repro:
    runs-on: windows-latest
    steps:
      - run: echo "print('Hello world!')" > index.py
      - uses: github/codeql-action/init@v2
        env: 
          PY_PYTHON3: 3.11
        with:
          languages: python
      - uses: github/codeql-action/analyze@v2
