on: push

jobs:
  repro:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: echo "print('Hello world!')" > index.py
      - uses: github/codeql-action/init@aeisenberg/python-3-12-fix
        with:
          languages: python
      - run: env
        shell: bash
      - run: |
          py -3 -c "import sys;print(sys.path)"
          py -3 -c "import imp"
      - uses: github/codeql-action/analyze@aeisenberg/python-3-12-fix
